// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHgmEg6LWIx1OItTDqCqkLxKESaspkZDI',
    appId: '1:562101749816:web:49954a3f0a64a06a40becd',
    messagingSenderId: '562101749816',
    projectId: 'scan-ca7d8',
    authDomain: 'scan-ca7d8.firebaseapp.com',
    storageBucket: 'scan-ca7d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF0wW8T-wDTJJQawG8SARTkn76pPDIOxs',
    appId: '1:562101749816:android:30ffa8aef5367e2d40becd',
    messagingSenderId: '562101749816',
    projectId: 'scan-ca7d8',
    storageBucket: 'scan-ca7d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFewHkLzxw0or5vO0YcxO7VzjT4msquUc',
    appId: '1:562101749816:ios:9594aad21587eefb40becd',
    messagingSenderId: '562101749816',
    projectId: 'scan-ca7d8',
    storageBucket: 'scan-ca7d8.appspot.com',
    iosClientId: '562101749816-ruq8p7e3pfqj1sj69mas2imkdp8qvpqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.vfproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFewHkLzxw0or5vO0YcxO7VzjT4msquUc',
    appId: '1:562101749816:ios:b20e09ca8ed03c8340becd',
    messagingSenderId: '562101749816',
    projectId: 'scan-ca7d8',
    storageBucket: 'scan-ca7d8.appspot.com',
    iosClientId: '562101749816-ahjt6dn1ce4su8o5ika0do5mu2v9qf9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.vfproj.RunnerTests',
  );
}
